In [289]:
import pandas as pd
import csv
import regex

In [290]:
teamsacr = ['CSK', 'DC', 'GT', 'KKR', 'LSG', 'MI', 'PBKS', 'RR', 'RCB', 'SRH']
teamsacr_before2022=['CSK','DC','KKR','MI','PBKS','RR','RCB','SRH']

In [291]:
team='SRH' #input from the site
folder="2022"
bat_stats=pd.read_csv(f"{folder}/{team}_Batstats.csv")
player_details=pd.read_csv(f"{folder}/{team}_players.csv")
bowl_stats=pd.read_csv(f"{folder}/{team}_Bowlstats.csv")

In [292]:
bat_stats["player_name"]=bat_stats["player_name"].str.upper()
bowl_stats["player_name"]=bowl_stats["player_name"].str.upper()

In [293]:
bat_stats=pd.merge(bat_stats,player_details,on=["player_name"])
bat_stats

,player_name,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s,player_id,player_role
0,ABHISHEK SHARMA,14,14,0,426,75,30.43,320,133.12,0,2,47,13,SRH109,All-Rounder
1,RAHUL TRIPATHI,14,14,3,413,76,37.55,261,158.23,0,3,40,20,SRH104,Batter
2,AIDEN MARKRAM,14,12,4,381,68*,47.63,274,139.05,0,3,25,19,SRH102,Batter
3,NICHOLAS POORAN,14,13,5,306,64*,38.25,212,144.33,0,2,16,21,SRH106,WK Keeper - Batter
4,KANE WILLIAMSON,13,13,2,216,57,19.64,231,93.50,0,1,16,8,SRH100,Batter
5,WASHINGTON SUNDAR,9,7,0,101,40,14.43,69,146.37,0,0,9,3,SRH112,All-Rounder
6,SHASHANK SINGH,10,5,1,69,25*,17.25,47,146.80,0,0,5,4,SRH108,Batter
7,ROMARIO SHEPHERD,3,3,1,58,26*,29.00,41,141.46,0,0,2,5,SRH111,All-Rounder
8,PRIYAM GARG,2,2,0,46,42,23.00,33,139.39,0,0,4,2,SRH103,Batter
9,BHUVNESHWAR KUMAR,14,6,3,24,8,8.00,26,92.30,0,0,3,0,SRH115,Bowler
10,SHREYAS GOPAL,1,1,1,9,9*,0.00,7,128.57,0,0,2,0,SRH114,All-Rounder
11,MARCO JANSEN,8,3,2,9,8*,9.00,7,128.57,0,0,0,1,SRH110,All-Rounder
12,SEAN ABBOTT,1,1,0,7,7,7.00,5,140.00,0,0,0,1,SRH113,All-Rounder
13,KARTIK TYAGI,2,2,0,7,7,3.50,6,116.66,0,0,1,0,SRH118,Bowler
14,ABDUL SAMAD,2,2,0,4,4,2.00,7,57.14,0,0,0,0,SRH101,Batter
15,UMRAN MALIK,14,4,3,4,3*,4.00,8,50.00,0,0,0,0,SRH121,Bowler
16,FAZALHAQ FAROOQI,3,1,1,2,2*,0.00,8,25.00,0,0,0,0,SRH116,Bowler
17,JAGADEESHA SUCHITH,5,2,0,2,2,1.00,8,25.00,0,0,0,0,SRH117,Bowler

In [294]:
bowl_stats=pd.merge(bowl_stats,player_details,on=["player_name"])
bowl_stats

,player_name,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w,player_id,player_role
0,UMRAN MALIK,14,14,49.1,444,22,25/5,20.18,9.03,13.40,1,1,SRH121,Bowler
1,T NATARAJAN,11,11,43.0,406,18,10/3,22.55,9.44,14.33,0,0,SRH120,Bowler
2,BHUVNESHWAR KUMAR,14,14,52.1,383,12,22/3,31.91,7.34,26.08,0,0,SRH115,Bowler
3,JAGADEESHA SUCHITH,5,5,18.0,140,7,12/2,20.00,7.77,15.42,0,0,SRH117,Bowler
4,MARCO JANSEN,8,8,32.0,274,7,25/3,39.14,8.56,27.42,0,0,SRH110,All-Rounder
5,WASHINGTON SUNDAR,9,8,28.0,239,6,21/2,39.83,8.53,28.00,0,0,SRH112,All-Rounder
6,ROMARIO SHEPHERD,3,3,9.0,98,3,42/2,32.66,10.88,18.00,0,0,SRH111,All-Rounder
7,FAZALHAQ FAROOQI,3,3,12.0,110,2,32/2,55.00,9.16,36.00,0,0,SRH116,Bowler
8,KARTIK TYAGI,2,2,8.0,79,1,42/1,79.00,9.87,48.00,0,0,SRH118,Bowler
9,AIDEN MARKRAM,14,4,6.0,64,1,8/1,64.00,10.66,36.00,0,0,SRH102,Batter
10,SHREYAS GOPAL,1,1,3.0,34,1,34/1,34.00,11.33,18.00,0,0,SRH114,All-Rounder
11,SEAN ABBOTT,1,1,4.0,47,1,47/1,47.00,11.75,24.00,0,0,SRH113,All-Rounder

In [295]:
#batter formula
bat_stats["total_score_bat"]=bat_stats["Runs"]*1.5+bat_stats["4s"]*0.5+bat_stats["6s"]-bat_stats["BF"]*0.5
bat_stats["total_score_bat"]/=10
bat_stats["total_score_bat"]+=(bat_stats["SR"]-120)/10+(bat_stats["Avg"]-30)/5
bat_stats=bat_stats.sort_values(by="total_score_bat",ascending=False)
bat_stats

,player_name,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s,player_id,player_role,total_score_bat
1,RAHUL TRIPATHI,14,14,3,413,76,37.55,261,158.23,0,3,40,20,SRH104,Batter,58.233
0,ABHISHEK SHARMA,14,14,0,426,75,30.43,320,133.12,0,2,47,13,SRH109,All-Rounder,52.948
2,AIDEN MARKRAM,14,12,4,381,68*,47.63,274,139.05,0,3,25,19,SRH102,Batter,52.031
3,NICHOLAS POORAN,14,13,5,306,64*,38.25,212,144.33,0,2,16,21,SRH106,WK Keeper - Batter,42.283
4,KANE WILLIAMSON,13,13,2,216,57,19.64,231,93.50,0,1,16,8,SRH100,Batter,17.728
5,WASHINGTON SUNDAR,9,7,0,101,40,14.43,69,146.37,0,0,9,3,SRH112,All-Rounder,11.973
7,ROMARIO SHEPHERD,3,3,1,58,26*,29.00,41,141.46,0,0,2,5,SRH111,All-Rounder,9.196
6,SHASHANK SINGH,10,5,1,69,25*,17.25,47,146.80,0,0,5,4,SRH108,Batter,8.780
8,PRIYAM GARG,2,2,0,46,42,23.00,33,139.39,0,0,4,2,SRH103,Batter,6.189
12,SEAN ABBOTT,1,1,0,7,7,7.00,5,140.00,0,0,0,1,SRH113,All-Rounder,-1.700
11,MARCO JANSEN,8,3,2,9,8*,9.00,7,128.57,0,0,0,1,SRH110,All-Rounder,-2.243
10,SHREYAS GOPAL,1,1,1,9,9*,0.00,7,128.57,0,0,2,0,SRH114,All-Rounder,-4.043
9,BHUVNESHWAR KUMAR,14,6,3,24,8,8.00,26,92.30,0,0,3,0,SRH115,Bowler,-4.720
13,KARTIK TYAGI,2,2,0,7,7,3.50,6,116.66,0,0,1,0,SRH118,Bowler,-4.834
14,ABDUL SAMAD,2,2,0,4,4,2.00,7,57.14,0,0,0,0,SRH101,Batter,-11.636
15,UMRAN MALIK,14,4,3,4,3*,4.00,8,50.00,0,0,0,0,SRH121,Bowler,-12.000
17,JAGADEESHA SUCHITH,5,2,0,2,2,1.00,8,25.00,0,0,0,0,SRH117,Bowler,-15.400
16,FAZALHAQ FAROOQI,3,1,1,2,2*,0.00,8,25.00,0,0,0,0,SRH116,Bowler,-15.600

In [296]:
bowl_stats["total_score_bowl"]=bowl_stats["Wkts"]*20-bowl_stats["Econ"]*2-bowl_stats["SR"]*0.5-bowl_stats["Avg"]*2
bowl_stats["total_score_bowl"]/=10
bowl_stats=bowl_stats.sort_values(by="total_score_bowl",ascending=False)
bowl_stats

,player_name,Mat,Inns,Ov,Runs,Wkts,BBI,Avg,Econ,SR,4w,5w,player_id,player_role,total_score_bowl
0,UMRAN MALIK,14,14,49.1,444,22,25/5,20.18,9.03,13.40,1,1,SRH121,Bowler,37.4880
1,T NATARAJAN,11,11,43.0,406,18,10/3,22.55,9.44,14.33,0,0,SRH120,Bowler,28.8855
2,BHUVNESHWAR KUMAR,14,14,52.1,383,12,22/3,31.91,7.34,26.08,0,0,SRH115,Bowler,14.8460
3,JAGADEESHA SUCHITH,5,5,18.0,140,7,12/2,20.00,7.77,15.42,0,0,SRH117,Bowler,7.6750
4,MARCO JANSEN,8,8,32.0,274,7,25/3,39.14,8.56,27.42,0,0,SRH110,All-Rounder,3.0890
5,WASHINGTON SUNDAR,9,8,28.0,239,6,21/2,39.83,8.53,28.00,0,0,SRH112,All-Rounder,0.9280
6,ROMARIO SHEPHERD,3,3,9.0,98,3,42/2,32.66,10.88,18.00,0,0,SRH111,All-Rounder,-3.6080
10,SHREYAS GOPAL,1,1,3.0,34,1,34/1,34.00,11.33,18.00,0,0,SRH114,All-Rounder,-7.9660
7,FAZALHAQ FAROOQI,3,3,12.0,110,2,32/2,55.00,9.16,36.00,0,0,SRH116,Bowler,-10.6320
11,SEAN ABBOTT,1,1,4.0,47,1,47/1,47.00,11.75,24.00,0,0,SRH113,All-Rounder,-10.9500
9,AIDEN MARKRAM,14,4,6.0,64,1,8/1,64.00,10.66,36.00,0,0,SRH102,Batter,-14.7320
8,KARTIK TYAGI,2,2,8.0,79,1,42/1,79.00,9.87,48.00,0,0,SRH118,Bowler,-18.1740

In [297]:
all_stats=pd.merge(bat_stats,bowl_stats,on="player_name",how="outer").fillna(0)
all_stats["total_score"]=all_stats["total_score_bat"]+all_stats["total_score_bowl"]
all_stats=all_stats.loc[all_stats["player_role_x"]=="All-Rounder"].sort_values(by="total_score",ascending=False)

In [298]:
t=dict(pd.concat([bat_stats.loc[bat_stats["player_role"]=="Batter"].head(4),bat_stats.loc[bat_stats["player_role"]=="WK Keeper - Batter"].head(1),all_stats.loc[all_stats["player_role_x"]=="All-Rounder"].head(3),bowl_stats.loc[bowl_stats["player_role"]=="Bowler"].head(3),],ignore_index=True)["player_name"])
if(len(t)==10):
    k=bowl_stats.loc[bowl_stats["player_role"]=="Bowler"]
    p = k.iloc[3]["player_name"]
    t[10]=p
    #t+=bowl_stats.loc[bowl_stats["player_role"]=="Bowler"][3]
t

{0: 'RAHUL TRIPATHI',
 1: 'AIDEN MARKRAM',
 2: 'KANE WILLIAMSON',
 3: 'SHASHANK SINGH',
 4: 'NICHOLAS POORAN',
 5: 'ABHISHEK SHARMA',
 6: 'WASHINGTON SUNDAR',
 7: 'ROMARIO SHEPHERD',
 8: 'UMRAN MALIK',
 9: 'T NATARAJAN',
 10: 'BHUVNESHWAR KUMAR'}